### ISSUE TITLE
AzureFunctionsPackage could not create Vfs.Dir from url

### ISSUE THREAD

**Issue by Barnarse** [lenala/azure-gradle-plugins#23]
Does anyone else have this problem? Looks like FunctionsTask.getOutputDirectory concats two paths with a colon, and prefixed with 'file:/' scheme which can not be converted to a URL. Console output below. Thanks!
```

> Task :azureFunctionsPackage
Step 1 of 6: Searching for Azure Function entry points
ClassPath to resolve: file:/Users/barneyspencer/Documents/src/Barnarse/multi-cloud-faas/abstracted-storage-example/gradle-diy/build/classes/java/main:/Users/barneyspencer/Documents/src/Barnarse/multi-cloud-faas/abstracted-storage-example/gradle-diy/build/generated/sources/annotationProcessor/java/main
could not create Vfs.Dir from url. ignoring the exception and continuing
org.reflections.ReflectionsException: could not create Vfs.Dir from url, no matching UrlType was found [file:/Users/barneyspencer/Documents/src/Barnarse/multi-cloud-faas/abstracted-storage-example/gradle-diy/build/classes/java/main:/Users/barneyspencer/Documents/src/Barnarse/multi-cloud-faas/abstracted-storage-example/gradle-diy/build/generated/sources/annotationProcessor/java/main]
either use fromURL(final URL url, final List<UrlType> urlTypes) or use the static setDefaultURLTypes(final List<UrlType> urlTypes) or addDefaultURLTypes(UrlType urlType) with your specialized UrlType.
        at org.reflections.vfs.Vfs.fromURL(Vfs.java:109)
        at org.reflections.vfs.Vfs.fromURL(Vfs.java:91)
        at org.reflections.Reflections.scan(Reflections.java:240)
        at org.reflections.Reflections.scan(Reflections.java:202)
        at org.reflections.Reflections.<init>(Reflections.java:123)
        at lenala.azure.gradle.functions.handlers.AnnotationHandlerImpl.findFunctions(AnnotationHandlerImpl.java:45)
        at lenala.azure.gradle.functions.PackageTask.findAnnotatedMethods(PackageTask.java:80)
        at lenala.azure.gradle.functions.PackageTask.packageFunction(PackageTask.java:49)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
...
```

**Comment by isaac-ipl** [comment]
I am getting same error trying to use `azureFunctionsPackage`, were you able to resolve this?

**Comment by bainss** [comment]
same here

**Comment by cniesen** [comment]
I'm getting the same issue (Windows and Linux).  A sample project is here: https://github.com/cniesen/azure-function-java

**Comment by Tetradeus** [comment]
Same here ...

**Comment by gotamafandy** [comment]
downgrading to gradle 5.1 will solve this error.

To downgrade: open your `gradle` directory in your project, change gradle-wrapper.properties's distributionUrl to `distributionUrl=https\://services.gradle.org/distributions/gradle-5.1-bin.zip`
