### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by lonpalmer** [lenala/azure-gradle-plugins#25]
I'm getting a null pointer exception when I try to package.

```
Caused by: java.lang.NullPointerException
        at lenala.azure.gradle.functions.FunctionsTask.getDeploymentStageDirectory(FunctionsTask.java:153)
        at lenala.azure.gradle.functions.PackageTask_Decorated.getDeploymentStageDirectory(Unknown Source)
        at lenala.azure.gradle.functions.PackageTask.writeHostJsonFile(PackageTask.java:156)
        at lenala.azure.gradle.functions.PackageTask.packageFunction(PackageTask.java:57)
        ... 41 more
```

**Comment by vbr738** [comment]
having this issue as well
